import {
  AiOutlineDashboard,
  AiOutlineToTop,
  AiOutlineWallet,
} from "react-icons/ai";
import { BiTransfer } from "react-icons/bi";
import { FiUser, FiSettings } from "react-icons/fi";
import {
  // GiReceiveMoney,
  GiTakeMyMoney,
} from "react-icons/gi";

import { MdOutlineSupportAgent } from "react-icons/md";
import { RiTeamLine, RiMoneyDollarCircleLine } from "react-icons/ri";
export const menus = [
  // ************************************* common dashboard menu ************************//
  {
    id: "337fwedkf",
    menu: "dashboard",
    icon: <AiOutlineDashboard />,
    route: "/dashboard",
    permission: ["user", "admin"],
  },
  // ************************************* admin dashboard menu ************************//
  {
    id: "7dfsegrr8srf",
    menu: "Member",
    icon: <FiUser />,
    permission: ["admin"],
    dropdown: [
      {
        id: "83agr89r4ifd",
        menu: "User Statistics",
        route: "/dashboard/member/team-statistics",
        permission: ["admin"],
      },
      {
        id: "83agr89r4ifd",
        menu: "All Member",
        route: "/dashboard/member/all-member",
        permission: ["admin"],
      },
      {
        id: "838dga9r4ifd",
        menu: "Active Member",
        route: "/dashboard/member/active-member",
        permission: ["admin"],
      },
      {
        id: "838dga9ifd",
        menu: "Blocked Member",
        route: "/dashboard/member/blocked-member",
        permission: ["admin"],
      },
    ],
  },
  {
    id: "7dfsrs8srf",
    menu: "Deposit",
    icon: <GiTakeMyMoney />,
    permission: ["admin"],
    dropdown: [
      {
        id: "83bhi9r4ifd",
        menu: "All Deposit",
        route: "/dashboard/deposit/all-deposit",
        permission: ["admin"],
      },
      {
        id: "838dsoifd",
        menu: "Successful Deposit",
        route: "/dashboard/deposit/successful-deposit",
        permission: ["admin"],
      },
      {
        id: "8shbga9ifd",
        menu: "Rejected Deposit",
        route: "/dashboard/deposit/rejected-deposit",
        permission: ["admin"],
      },
    ],
  },
  {
    id: "ajjdrs8srf",
    menu: "withdraw",
    icon: <AiOutlineWallet />,
    permission: ["admin"],
    dropdown: [
      {
        id: "vmsssvfsfsf",
        menu: "All Auto Trade Withdraw",
        route: "/dashboard/Withdraw/all-auto-trade-withdraw",
        permission: ["admin"],
      },
      {
        id: "dajei9r4ifd",
        menu: "All Withdraw",
        route: "/dashboard/Withdraw/all-withdraw",
        permission: ["admin"],
      },
      {
        id: "ajobeoifd",
        menu: "Successful Withdraw",
        route: "/dashboard/Withdraw/successful-withdraw",
        permission: ["admin"],
      },
      {
        id: "aubia9ifd",
        menu: "Rejected Withdraw",
        route: "/dashboard/Withdraw/rejected-withdraw",
        permission: ["admin"],
      },
    ],
  },
  {
    id: "ajrgrs8rrf",
    menu: "Fund Transfer",
    icon: <BiTransfer />,
    permission: ["admin"],
    dropdown: [
      {
        id: "dajbaksjbd",
        menu: "Fund Transfer",
        route: "/dashboard/transfer/fund-transfer",
        permission: ["admin"],
      },
      {
        id: "dajbaksjbd",
        menu: "Fund History",
        route: "/dashboard/transfer/fund-history",
        permission: ["admin"],
      },
      {
        id: "3892tghb43tufu67",
        menu: "All Fund History",
        route: "/dashboard/transfer/all-fund-history",
        permission: ["admin"],
      },
      {
        id: "3892tghb43tufu67",
        menu: "User Topup History",
        route: "/dashboard/transfer/user-topup-history",
        permission: ["admin"],
      },
      {
        id: "dajbaksjbd",
        menu: "Bonanza Transfer",
        route: "/dashboard/transfer/bonanza-transfer",
        permission: ["admin"],
      },
      {
        id: "dajbaksjbd",
        menu: "Bonanza Transfer History",
        route: "/dashboard/transfer/bonanza-transfer-history",
        permission: ["admin"],
      },
      {
        id: "dajbaksjbd",
        menu: "Royalty Income",
        route: "/dashboard/transfer/royalty-income",
        permission: ["admin"],
      },
      {
        id: "dajba4qefksjbd",
        menu: "Royalty Income History",
        route: "/dashboard/transfer/royalty-income-history",
        permission: ["admin"],
      },
      {
        id: "7843gtf283g",
        menu: "Gift Income Transfer",
        route: "/dashboard/transfer/gift-income-transfer",
        permission: ["admin"],
      },
      {
        id: "379t239q47g913",
        menu: "Gift Income Transfer History",
        route: "/dashboard/transfer/gift-income-transfer-history",
        permission: ["admin"],
      },
    ],
  },
  {
    id: "4343qf3q2f",
    menu: "earning",
    icon: <GiTakeMyMoney />,
    permission: ["admin"],
    dropdown: [
      {
        id: "q4gf4qgq23fq5",
        menu: "Direct Income",
        route: "/dashboard/earnings/direct-income",
        permission: ["admin"],
      },
      {
        id: "34qqf43gq3hq",
        menu: "Indirect Income",
        route: "/dashboard/earnings/indirect-income",
        permission: ["admin"],
      },
      {
        id: "63j4h366rh4se",
        menu: "Auto Pool income",
        route: "/dashboard/earnings/auto-pool-income",
        permission: ["admin"],
      },
      {
        id: "45s8sf7025",
        menu: "Bonanza income",
        route: "/dashboard/earnings/bonanza-reward-income",
        permission: ["admin"],
      },
      {
        id: "158hs641nvgt",
        menu: "Bonanza achievers",
        route: "/dashboard/earnings/bonanza-achievers",
        permission: ["admin"],
      },
      {
        id: "347g287bq2783ae",
        menu: "List of Achievers",
        route: "/dashboard/earnings/list-of-achievers",
        permission: ["admin"],
      },
      {
        id: "5h4w45g45h5",
        menu: "Income Level Update",
        route: "/dashboard/earnings/income-level-update",
        permission: ["admin"],
      },
      {
        id: "q2q3t43wwe3rg",
        menu: "Direct Withdraw Income",
        route: "/dashboard/earnings/direct-withdraw-income",
        permission: ["admin"],
      },
      {
        id: "75j6t7jr6eh",
        menu: "Booster income",
        route: "/dashboard/earnings/booster-income",
        permission: ["admin"],
      },
      {
        id: "7syfsf7nvjsu",
        menu: "Booster Upgrade income",
        route: "/dashboard/earnings/booster-upgrade-income",
        permission: ["admin"],
      },
      {
        id: "5f8ss8f8sfs",
        menu: "Booster Controller",
        route: "/dashboard/earnings/booster-controller",
        permission: ["admin"],
      },
      {
        id: "5563yhe5yyh56",
        menu: "Gift income",
        route: "/dashboard/earnings/gift-income",
        permission: ["admin"],
      },
      // {
      //   id: "w3tg4w3gwt5hhy54",
      //   menu: "Royalty income",
      //   route: "/dashboard/earnings/royalty-income",
      //   permission: ["admin"],
      // },
    ],
  },
  {
    id: "vs8s8fsf",
    menu: "Auto Trade",
    icon: <MdOutlineSupportAgent />,
    permission: ["admin"],
    dropdown: [
      {
        id: "1sf4sf8s8s5f",
        menu: "Auto Trade Users",
        route: "/dashboard/trade/auto-trade-users",
        permission: ["admin"],
      },
      {
        id: "12vnfs5fse",
        menu: "Auto Trade Upgrade History",
        route: "/dashboard/trade/auto-trade-upgrade-history",
        permission: ["admin"],
      },
      {
        id: "vm8s5s5fslfos",
        menu: "Auto Trade Income History",
        route: "/dashboard/trade/auto-trade-income-history",
        permission: ["admin"],
      },
    ],
  },
  {
    id: "nf4au4awg43",
    menu: "Support",
    icon: <MdOutlineSupportAgent />,
    permission: ["admin"],
    dropdown: [
      {
        id: "naiuh3h33x",
        menu: "Create News",
        route: "/dashboard/create-news",
        permission: ["admin"],
      },
      {
        id: "98ay9uva",
        menu: "Contact Us",
        route: "/dashboard/contact-us",
        permission: ["admin"],
      },
      {
        id: "30ht9fwa",
        menu: "Ticket Data",
        route: "/dashboard/ticket-data",
        permission: ["admin"],
      },
    ],
  },
  {
    id: "sf4s8f7ser",
    menu: "Setting",
    icon: <FiSettings />,
    permission: ["admin"],
    dropdown: [
      {
        id: "f4s8fe8r8",
        menu: "Change Password",
        route: "/dashboard/change-password",
        permission: ["admin"],
      },
      {
        id: "sf4se8r9w",
        menu: "Popup Image",
        route: "/dashboard/popup-image",
        permission: ["admin"],
      },
      {
        id: "sf4se8r9w",
        menu: "Auto Pool Controller",
        route: "/dashboard/auto-pool-controller",
        permission: ["admin"],
      },
      {
        id: "sf4se8r9w",
        menu: "Video Controller",
        route: "/dashboard/video-controller",
        permission: ["admin"],
      },
      {
        id: "sf4se8r9w",
        menu: "PDF Controller",
        route: "/dashboard/pdf-controller",
        permission: ["admin"],
      },
    ],
  },
  // ************************************* user dashboard menu ************************//
  {
    id: "7dfser8srf",
    menu: "profile",
    icon: <FiUser />,
    permission: ["user"],
    dropdown: [
      {
        id: "8389r4ifd",
        menu: "my profile",
        route: "/dashboard/profile/my-profile",
        permission: ["user"],
      },
      {
        id: "f7d8e8sfrw",
        menu: "Update profile",
        route: "/dashboard/profile/update-profile",
        permission: ["user"],
      },
      {
        id: "sf7s8f5s8er",
        menu: "Update password",
        route: "/dashboard/profile/update-password",
        permission: ["user"],
      },
      {
        id: "f7s5f8se8r",
        menu: "Update trx password",
        route: "/dashboard/profile/update-trxPassword",
        permission: ["user"],
      },
      {
        id: "sfs4f8se8",
        menu: "Update email",
        route: "/dashboard/profile/update-email",
        permission: ["user"],
      },
      {
        id: "d7f8wer8s",
        menu: "Update wallet",
        route: "/dashboard/profile/update-wallet",
        permission: ["user"],
      },
    ],
  },
  {
    id: "f7df8sfd7f",
    menu: "my wallet",
    icon: <AiOutlineWallet />,
    permission: ["user"],
    dropdown: [
      {
        id: "7854s8dfs5d",
        menu: "wallet",
        route: "/dashboard/wallet/my-wallet",
        permission: ["user"],
      },
      {
        id: "8s8dfdepser",
        menu: "deposit fund",
        icon: <RiMoneyDollarCircleLine />,
        route: "/dashboard/wallet/deposit-fund",
        permission: ["user"],
      },
      {
        id: "fd7d8s48574",
        menu: "deposit history",
        route: "/dashboard/wallet/deposit-history",
        permission: ["user"],
      },
      // {
      //   id: "348gfb74q3749g",
      //   menu: "Fund Receiving History",
      //   route: "/dashboard/wallet/fund-receiving-history",
      //   permission: ["user"],
      // },
    ],
  },
  {
    id: "df79er8suf",
    menu: "team",
    icon: <RiTeamLine />,
    permission: ["user"],
    dropdown: [
      {
        id: "r3er8re8sdf7dn",
        menu: "direct team",
        route: "/dashboard/team/direct-team",
        permission: ["user"],
      },
      {
        id: "fs7erw55s",
        menu: "level team",
        route: "/dashboard/team/level-team",
        permission: ["user"],
      },
    ],
  },
  {
    id: "m5vko5f5sfo3s5f",
    menu: "Top up",
    icon: <AiOutlineToTop />,
    permission: ["user"],
    dropdown: [
      {
        id: "4f5sf8s85sff5",
        menu: "auto pool enter",
        route: "/dashboard/topup/autopool-enter",
        permission: ["user"],
      },
      {
        id: "fnd5fhs5or5f",
        menu: "topup account",
        route: "/dashboard/topup/topup-account",
        permission: ["user"],
      },
      {
        id: "vnzs5dajio5df8",
        menu: "topup history",
        route: "/dashboard/topup/topup-history",
        permission: ["user"],
      },
      // {
      //   id: "vnz5s45dajio5df8",
      //   menu: "Upgrade Auto Pool",
      //   route: "/dashboard/topup/upgrade-autopool",
      //   permission: ["user"],
      // },
      // {
      //   id: "vnzsdaj42iodf8",
      //   menu: "Upgrade Auto Pool history",
      //   route: "/dashboard/topup/upgrade-autopool-history",
      //   permission: ["user"],
      // },
      {
        id: "3t87ghq7q829h4g9q",
        menu: "Booster Upgrade",
        route: "/dashboard/topup/booster-income",
        permission: ["user"],
      },
      {
        id: "23gf43wg4g",
        menu: "Booster Upgrade history",
        route: "/dashboard/topup/upgrade-Booster-history",
        permission: ["user"],
      },
      {
        id: "4f8sf8s8fs8",
        menu: "Auto Trade Upgrade",
        route: "/dashboard/topup/auto-trade-upgrade",
        permission: ["user"],
      },
      {
        id: "nvjuus8f8s8fs",
        menu: "Auto Trade Upgrade history",
        route: "/dashboard/topup/auto-trade-upgrade-history",
        permission: ["user"],
      },
      {
        id: "45s8fs88fsf",
        menu: "Auto Trade User topup",
        route: "/dashboard/topup/auto-trade-user-topup",
        permission: ["user"],
      },
      {
        id: "23sf9svnsqzys",
        menu: "Auto Trade User topup History",
        route: "/dashboard/topup/auto-trade-user-topup-history",
        permission: ["user"],
      },
    ],
  },
  {
    id: "fsfsfusf8se4r",
    menu: "earning",
    icon: <GiTakeMyMoney />,
    permission: ["user"],
    dropdown: [
      {
        id: "ha4db4vds4bd3h",
        menu: "Earning statistics",
        route: "/dashboard/earnings/earning-statistics",
        permission: ["user"],
      },
      {
        id: "e7rfs5fs4532nbv",
        menu: "Direct Income",
        route: "/dashboard/earnings/direct-income",
        permission: ["user"],
      },
      {
        id: "e7rfs5fs25gsenbv",
        menu: "Indirect Income",
        route: "/dashboard/earnings/indirect-income",
        permission: ["user"],
      },
      {
        id: "f7e4rf34234fwre223se5rp",
        menu: "Auto Pool income",
        route: "/dashboard/earnings/auto-pool-income",
        permission: ["user"],
      },
      {
        id: "48s8ser",
        menu: "Bonanza income",
        route: "/dashboard/earnings/bonanza-reward-income",
        permission: ["user"],
      },
      {
        id: "hfs6syfjsjer",
        menu: "Bonanza achieve",
        route: "/dashboard/earnings/bonanza-achieve",
        permission: ["user"],
      },
      {
        id: "88j7fs6s6eh",
        menu: "Bonanza prize",
        route: "/dashboard/earnings/bonanza-prize",
        permission: ["user"],
      },
      {
        id: "f7fbc452bcwf424f5d",
        menu: "Income Level Update",
        route: "/dashboard/earnings/income-level-update",
        permission: ["user"],
      },
      {
        id: "f7ewt3rfs4e44s3rp",
        menu: "Direct Withdraw Income",
        route: "/dashboard/earnings/direct-withdraw-income",
        permission: ["user"],
      },
      {
        id: "f7er24f34ser425p1",
        menu: "Booster income",
        route: "/dashboard/earnings/booster-income",
        permission: ["user"],
      },
      {
        id: "58f8ss5se8",
        menu: "Booster Upgrade income",
        route: "/dashboard/earnings/booster-upgrade-income",
        permission: ["user"],
      },
      {
        id: "f47erf3swer44er25p",
        menu: "Gift income",
        route: "/dashboard/earnings/gift-income",
        permission: ["user"],
      },
      {
        id: "03s5s8s8fs",
        menu: "Auto Trade income",
        route: "/dashboard/earnings/auto-trade-income",
        permission: ["user"],
      },
      {
        id: "ny6fs5f6fysf",
        menu: "Auto Trade Referral",
        route: "/dashboard/earnings/auto-trade-referral",
        permission: ["user"],
      },
      // {
      //   id: "f47er452f3se4r25p",
      //   menu: "Royalty income",
      //   route: "/dashboard/earnings/royalty-income",
      //   permission: ["user"],
      // },
    ],
  },
  {
    id: "bv2sre2ws7sf",
    menu: "withdraw",
    icon: <BiTransfer />,
    permission: ["user"],
    dropdown: [
      {
        id: "vv4mk4ufi4sf",
        menu: "withdraw funds",
        route: "/dashboard/withdraw/withdraw-fund",
        permission: ["user"],
      },
      {
        id: "vn2sff47s7f7d",
        menu: "withdraw history",
        route: "/dashboard/withdraw/withdraw-history",
        permission: ["user"],
      },
      {
        id: "v1s8s8fs8fse",
        menu: "Auto Trade Withdraw",
        route: "/dashboard/withdraw/auto-trade-withdraw",
        permission: ["user"],
      },
      {
        id: "5f8s8fs81s4f7s",
        menu: "Auto Trade Withdraw history",
        route: "/dashboard/withdraw/auto-trade-withdraw-history",
        permission: ["user"],
      },
    ],
  },
  {
    id: "b4v2sr4e2ws7s5f",
    menu: "Fund Transfer",
    icon: <BiTransfer />,
    permission: ["user"],
    dropdown: [
      {
        id: "47qg4gf734q34vq3",
        menu: "User Top Up",
        route: "/dashboard/fund/top-up",
        permission: ["user"],
      },
      {
        id: "3q08gh93q9r3q",
        menu: "User Top Up History",
        route: "/dashboard/fund/top-up-history",
        permission: ["user"],
      },
      {
        id: "sfs57e4fewr8s8e5r",
        menu: "Fund Transfer ",
        route: "/dashboard/fund/fund-transfer",
        permission: ["user"],
      },
      {
        id: "sfs337er8s834gw3er",
        menu: "Fund Transfer History",
        route: "/dashboard/fund/fund-transfer-history",
        permission: ["user"],
      },
    ],
  },
  {
    id: "vn3es6uru3sf7",
    menu: "support",
    icon: <MdOutlineSupportAgent />,
    permission: ["user"],
    dropdown: [
      {
        id: "sfs4f4s8e8r",
        menu: "updates",
        route: "/dashboard/support/updates",
        permission: ["user"],
      },
      {
        id: "vmj4dfs4f8sf",
        menu: "support ticket",
        route: "/dashboard/support/support-ticket",
        permission: ["user"],
      },
      {
        id: "vmj4de4ru4sf7s7",
        menu: "ticket history",
        route: "/dashboard/support/ticket-history",
        permission: ["user"],
      },
      {
        id: "f7s8f8fd",
        menu: "Contact Us",
        route: "/dashboard/support/contact-us",
        permission: ["user"],
      },
      {
        id: "w83grt32b",
        menu: "ContactUs History",
        route: "/dashboard/support/contact-us-history",
        permission: ["user"],
      },
    ],
  },
];
